language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
# command to install dependencies
install: ./travis-install.sh
script: ./travis-test.sh
after_success: coveralls